#
# Executes commands at login pre-zshrc.
#
# ".zprofile is meant as an alternative to .zlogin for ksh fans;
# the two are not intended to be used together, although
# this could certainly be done if desired."
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

# kitty config dir
export KITTY_CONFIG_DIRECTORY="$HOME/dotfiles/gui_terminals/kitty"

# default RAILS environment
RAILS_ENV="development"
