#
# Defines environment variables.
#
# .zshenv is always sourced, it often contains exported variables
# that should be available to other programs.
# For example, $PATH, $EDITOR, and $PAGER
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# load custom environment
source $HOME/.zsh_env
