#
# Defines environment variables.
#
# .zshenv is always sourced, it often contains exported variables
# that should be available to other programs.
# For example, $PATH, $EDITOR, and $PAGER
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
