# vim:syntax=zsh
# vim:filetype=zsh

# startup speed benchmarks
# https://htr3n.github.io/2018/07/faster-zsh/
# uncomment the line below, then source .zshrc and run zprof.
#zmodload zsh/zprof

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# overrides theme set in .zpreztorc
prompt powerlevel10k

# enable or disable custom themes on the fly
CUSTOM_THEMES_ENABLED=0

# load custom themes
if [[ CUSTOM_THEMES_ENABLED -eq 1 && -d $HOME/.zsh_user_themes ]]; then
  # file namings must be: prompt_THEMENAME_setup
  fpath=( $HOME/.zsh_user_themes $fpath )
  autoload -Uz promptinit; promptinit
  # set a custom theme here. This overrides .zpreztorc theme setting.
  prompt sorinEdit
fi

# custom history size
export HISTSIZE=20000
# save history after logout
export SAVEHIST=20000
# history file
export HISTFILE=~/.zsh_history

autoload zmv

# pyenv addition setup
# as per https://github.com/pyenv/pyenv/
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

# bash autocompletion
autoload -Uz bashcompinit
bashcompinit
for file in $HOME/dotfiles/bash/completions/*(.); source $file

# autocompletion
if [ -d $HOME/dotfiles/zsh/completions ]; then fpath=($HOME/dotfiles/zsh/completions $fpath); fi
autoload -Uz compinit
compinit

# load interactive env
source $HOME/dotfiles/zsh/common/zsh_env_interactive

# load aliases
source $HOME/dotfiles/zsh/common/zsh_aliases

# lazy-load functions
fpath=($fpath ~/dotfiles/zsh/autoloaded)
for file in $(ls -1 ~/dotfiles/zsh/autoloaded); do
  autoload -Uz $file
done

# load custom/env specific stuff, but only if file exists
if [[ -a $HOME/.zsh_custom ]]; then
source $HOME/.zsh_custom
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# aws-cli autocomplete
if [ ! -z $(command -v aws_completer) ]; then
  complete -C 'aws_completer' aws
fi

# tabtab source for packages
# uninstall by removing these lines
[[ -f ~/.config/tabtab/__tabtab.zsh ]] && . ~/.config/tabtab/__tabtab.zsh || true

# run every time to cd into a directory
function chpwd {
  # things to do each time you change directory. Zsh will call this.
  check_nvmrc
}

check_nvmrc() {
  if [[ -f .nvmrc ]] && [[ "$(cat .nvmrc)" != "$(node --version)" ]]; then
    nvm use
  fi
}

# run in for every new shell
check_nvmrc

