[metadata]
name = "dotfiles"
description = "A channel to select from your user's dotfiles"
requirements = [ "fd", "batcat",]

[source]
command = "fd -t f . $HOME/dotfiles"

[preview]
command = "batcat -n --color=always '{}'"

[keybindings]
shortcut = "f4"

