[metadata]
name = "diff"
description = "A channel to select files from git diff commands"
requirements = [ "git",]

[source]
command = "git diff --name-only HEAD"

[ui]
preview_panel = { "size" = 70, "scrollbar" = true }

[preview]
command = "git diff HEAD --color=always -- '{}'"

