[metadata]
name = "br"
description = "A channel to select from git branches"
requirements = [ "git",]

[source]
command = "git --no-pager branch --all --format=\"%(refname:short)\""
output = "{split: :0}"

[ui]
preview_panel = { "size" = 70, "scrollbar" = true }

[preview]
command = "git show -p --stat --pretty=fuller --color=always '{0}'"

