code --install-extension aykutsarac.jsoncrack-vscode
code --install-extension bierner.github-markdown-preview
code --install-extension bierner.markdown-yaml-preamble
code --install-extension cesium.gltf-vscode
code --install-extension christian-kohler.npm-intellisense
code --install-extension cloudedcat.vscode-model-viewer
code --install-extension dbaeumer.vscode-eslint
code --install-extension devadvice.serverlessconsole
code --install-extension dotjoshjohnson.xml
code --install-extension dunstontc.viml
code --install-extension editorconfig.editorconfig
code --install-extension esbenp.prettier-vscode
code --install-extension github.codespaces
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.remotehub
code --install-extension github.vscode-github-actions
code --install-extension github.vscode-pull-request-github
code --install-extension hediet.vscode-drawio
code --install-extension ionide.ionide-fsharp
code --install-extension ionutvmi.path-autocomplete
code --install-extension kachick.vscode-yamlfmt
code --install-extension kdl-org.kdl-v1
code --install-extension mads-hartmann.bash-ide-vscode
code --install-extension mark-wiemer.vscode-autohotkey-plus-plus
code --install-extension marp-team.marp-vscode
code --install-extension mikestead.dotenv
code --install-extension mrmlnc.vscode-duplicate
code --install-extension ms-azure-devops.azure-pipelines
code --install-extension ms-azure-load-testing.microsoft-testing
code --install-extension ms-azuretools.azure-dev
code --install-extension ms-azuretools.vscode-azure-github-copilot
code --install-extension ms-azuretools.vscode-azure-mcp-server
code --install-extension ms-azuretools.vscode-azureappservice
code --install-extension ms-azuretools.vscode-azurecontainerapps
code --install-extension ms-azuretools.vscode-azureresourcegroups
code --install-extension ms-azuretools.vscode-azurestaticwebapps
code --install-extension ms-azuretools.vscode-azurestorage
code --install-extension ms-azuretools.vscode-azureterraform
code --install-extension ms-azuretools.vscode-azurevirtualmachines
code --install-extension ms-azuretools.vscode-containers
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csdevkit
code --install-extension ms-dotnettools.csharp
code --install-extension ms-dotnettools.dotnet-interactive-vscode
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-dotnettools.vscodeintellicode-csharp
code --install-extension ms-edgedevtools.vscode-edge-devtools
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.debugpy
code --install-extension ms-python.isort
code --install-extension ms-python.pylint
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-python.vscode-python-envs
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.azure-repos
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.remote-repositories
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-windows-ai-studio.windows-ai-studio
code --install-extension redhat.java
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension rust-lang.rust-analyzer
code --install-extension sdras.night-owl
code --install-extension shopify.ruby-lsp
code --install-extension snyk-security.snyk-vulnerability-scanner
code --install-extension sonarsource.sonarlint-vscode
code --install-extension spmeesseman.vscode-taskexplorer
code --install-extension stylelint.vscode-stylelint
code --install-extension sumneko.lua
code --install-extension tamasfe.even-better-toml
code --install-extension teamsdevapp.vscode-ai-foundry
code --install-extension tomoki1207.pdf
code --install-extension uyiosa-enabulele.reopenclosedtab
code --install-extension vadimcn.vscode-lldb
code --install-extension visualstudioexptteam.intellicode-api-usage-examples
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension vmware.vscode-spring-boot
code --install-extension vscjava.vscode-gradle
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vsls-contrib.gistfs
code --install-extension vue.volar
code --install-extension wayou.vscode-todo-highlight
code --install-extension will-stone.plastic
code --install-extension willasm.rc-script
code --install-extension xshrim.txt-syntax
code --install-extension yzhang.markdown-all-in-one
code --install-extension zignd.html-css-class-completion
