code --install-extension 42Crunch.vscode-openapi
code --install-extension AdrianSanguineti.json-parse-validator
code --install-extension agauniyal.vscode-caniuse
code --install-extension akamud.vscode-caniuse
code --install-extension alefragnani.Bookmarks
code --install-extension amazonwebservices.aws-toolkit-vscode
code --install-extension Angular.ng-template
code --install-extension astallinger.sourcetrail
code --install-extension bmuskalla.vscode-tldr
code --install-extension ccimage.jsonviewer
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension chrmarti.ssh
code --install-extension codezombiech.gitignore
code --install-extension cschleiden.vscode-github-actions
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension devadvice.serverlessconsole
code --install-extension DotJoshJohnson.xml
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.code-runner
code --install-extension GitHub.vscode-codeql
code --install-extension GitHub.vscode-pull-request-github
code --install-extension hangxingliu.vscode-nginx-conf-hint
code --install-extension hbenl.vscode-test-explorer
code --install-extension jonsmithers.open-in-vim
code --install-extension mads-hartmann.bash-ide-vscode
code --install-extension mark-tucker.aws-cli-configure
code --install-extension mindaro-dev.file-downloader
code --install-extension mindaro.mindaro
code --install-extension mrmlnc.vscode-duplicate
code --install-extension ms-azure-devops.azure-pipelines
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.hexeditor
code --install-extension ms-vscode.test-adapter-converter
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-audio
code --install-extension ms-vsliveshare.vsliveshare-pack
code --install-extension octref.vetur
code --install-extension ph1p.zeit-co-vscode-schemas
code --install-extension piotrpalarz.vscode-gitignore-generator
code --install-extension Pivotal.vscode-boot-dev-pack
code --install-extension Pivotal.vscode-spring-boot
code --install-extension redhat.fabric8-analytics
code --install-extension redhat.java
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension rogalmic.bash-debug
code --install-extension rust-lang.rust
code --install-extension snyk-security.snyk-vulnerability-scanner
code --install-extension SonarSource.sonarlint-vscode
code --install-extension spmeesseman.vscode-taskexplorer
code --install-extension svelte.svelte-vscode
code --install-extension takkaO.open-window-tab-context
code --install-extension ThreadHeap.serverless-ide-vscode
code --install-extension thundra.thundra-debugger
code --install-extension tomoki1207.pdf
code --install-extension vadimcn.vscode-lldb
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscjava.vscode-spring-boot-dashboard
code --install-extension vscjava.vscode-spring-initializr
code --install-extension xshrim.txt-syntax
