import = [
  # import common config
  "~\\dotfiles\\terminals\\alacritty\\common.toml",
  "~\\dotfiles\\terminals\\alacritty\\keybindings.toml",
  # import themes
  "~\\dotfiles\\terminals\\alacritty\\themes\\paprika-by-pirafrank.toml"
]

[shell]
program = 'pwsh.exe'
