# shell not specified, going with user's default one

import = [
  # import common config
  "~/dotfiles/terminals/alacritty/common.toml",
  "~/dotfiles/terminals/alacritty/keybindings.toml",
  # import themes
  "~/dotfiles/terminals/alacritty/themes/one-dark-by-themer-dot-dev.toml"
]
